### ISSUE TITLE
apcups_status shows multiple status concurrently

### ISSUE THREAD

**Issue by candlerb** [damomurf/apcupsd-exporter#2]
Firstly, thank you for writing this exporter.  It was just what I was looking for!

There seems to be a problem with the `apcups_status` metric(s).

After removing and reapplying the input voltage to the UPS, I now get two time series, both with value 1.  That is, the device appears to be both "online" and "onbatt" simultaneously!

~~~
$ curl http://nuc2.x.x.x:8080/metrics | grep status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8909  100  8909    0     0   680k      0 --:--:-- --:--:-- --:--:--  725k
# HELP apcups_status Current status of UPS
# TYPE apcups_status gauge
apcups_status{hostname="nuc2.x.x.x",status="onbatt",upsname="bx700"} 1
apcups_status{hostname="nuc2.x.x.x",status="online",upsname="bx700"} 1
~~~

I imagine this comes from behaviour of the underlying [client_golang/prometheus](https://github.com/prometheus/client_golang) library.  Maybe when a time series stops generating valid data, it keeps returning the most recent value?

Options for fixing this:

1. Use the current approach, fixed to avoid overlapping time series:

    ~~~
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="online"} 1
    ... later ...
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="onbatt"} 1
    ~~~

    I do think this is actually rather inconvenient to use though.  Basically the "online" timeseries shows 1 when the device is online, and NULL when the device is offline (*or* when prometheus fails to collect data).

    Making a grafana widget to show this accurately is not straightforward, nor is alerting on this.  For example, the behaviour of a grafana [singlestat](http://docs.grafana.org/features/panels/singlestat/) panel:

    > current - The last value in the series. If the series ends on null the previous value will be used.

    This makes it hard to have an indicator which shows whether the UPS is currently online/onbatt.

2. Change to a single time series, where the data value is (e.g.) 0 for "onbatt" and 1 for "online".

    ~~~
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700"} 1
    ... later ...
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700"} 0
    ~~~

    This is my preferred option; it would be a lot more convenient for reporting and alerting. It does involve mapping the possible status strings to numbers, since prometheus only stores numbers.  (It is straightforward to map them back to strings in grafana though).

3. Have multiple time series, all of which report 0 and 1 values

    ~~~
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="online"} 1
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="onbatt"} 0
    ... later ...
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="online"} 0
    apcups_status{hostname="nuc2.x.x.x",upsname="bx700",status="onbatt"} 1
    ~~~

    This carries the string in a label, but is wasteful as it essentially duplicates the time series.

**Comment by damomurf** [comment]
@candlerb Thanks for the informative issue posting. There's definitely an issue with my code that doesn't deal with the switching of the status from apcupsd correctly.

Option 3, to me, seems the most Prometheus-like and is a lot clearer to someone who doesn't know the ins-and-outs of apcupsd and will need to translate a relatively obscure numeric value into a status.

That said, I appreciate how difficult that can make creating things like singlestat panels in Grafana - I've had the same issue with Elasticsearch exporters. Grafana really needs a way of extracting label values in panels.

I'm not particularly concerned about the waste, we're not talking about a huge number of metrics here, so what about the approach of fixing the underlying problem and delivering option 3, and then some kind of an `apcups_status_all` metric that does the translation into a single integer also?

I should be able to spend some time adjacent to my ups in the next few days and should be able to come up with a fix as proposed.

**Comment by candlerb** [comment]
Aside: I came across [this text](https://prometheus.io/docs/alerting/rules/#inspecting-alerts-during-runtime) in prometheus documentation:

> For pending and firing alerts, Prometheus also stores synthetic time series of the form `ALERTS{alertname="<alert name>", alertstate="pending|firing", <additional alert labels>}`. The sample value is set to `1` as long as the alert is in the indicated active (pending or firing) state, and a single `0` value gets written out when an alert transitions from active to inactive state. Once inactive, the time series does not get further updates.

So that might be another way to deal with it - i.e. just write a single 0 after the label is no longer current.  Then you only have to remember one previous label value.

Pseudocode:

~~~
IF current_state != last_state THEN
    write_label(status=last_state, value=0)
    last_state := current_state 
ENDIF
write_label(status=current_state, value=1)
~~~

In practice I'd probably still use the integer mapped timeseries though.

**Comment by damomurf** [comment]
@candlerb I think the latest code merged in addresses the original issue as well as adding a single metric that can be used?

**Comment by candlerb** [comment]
Thanks, I'll test in next couple of days

**Comment by candlerb** [comment]
Works for me - thanks!

~~~
-- when on battery
# HELP apcups_status Current status of UPS
# TYPE apcups_status gauge
apcups_status{hostname="nuc2.x.x.x",status="boost",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="commlost",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="lowbatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="nobatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="onbatt",upsname="bx700"} 1
apcups_status{hostname="nuc2.x.x.x",status="online",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="overload",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="replacebatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="shutting down",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="slave",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="slavedown",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="trim",upsname="bx700"} 0
# HELP apcups_status_numeric Current status of UPS represented as integer
# TYPE apcups_status_numeric gauge
apcups_status_numeric{hostname="nuc2.x.x.x",upsname="bx700"} 1

-- when online
# HELP apcups_status Current status of UPS
# TYPE apcups_status gauge
apcups_status{hostname="nuc2.x.x.x",status="boost",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="commlost",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="lowbatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="nobatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="onbatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="online",upsname="bx700"} 1
apcups_status{hostname="nuc2.x.x.x",status="overload",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="replacebatt",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="shutting down",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="slave",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="slavedown",upsname="bx700"} 0
apcups_status{hostname="nuc2.x.x.x",status="trim",upsname="bx700"} 0
# HELP apcups_status_numeric Current status of UPS represented as integer
# TYPE apcups_status_numeric gauge
apcups_status_numeric{hostname="nuc2.x.x.x",upsname="bx700"} 0
~~~

Shame that prometheus doesn't support string data values like [influxdb](https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#data-types)...

**Comment by candlerb** [comment]
As is turns out, according to [apcaccess](https://www.systutorials.com/docs/linux/man/8-apcaccess/) manpage, multiple status flags can be active simultaneously:

```
     STATUS      : UPS status.  One or more of the following (space-separated):
                 CAL TRIM BOOST ONLINE ONBATT OVERLOAD LOW‐BATT REPLACEBATT NOBATT SLAVE SLAVEDOWN
                 or
                 COMMLOST
                 or
                 SHUTTING DOWN
```

So it's perfectly reasonable to have separate time series for each.

OTOH I don't think apcupsd-exporter supports this - only exact match of a single flag.  (In practice I think multiple flags would be rare.  ONBATT and LOW-BATT perhaps? But I have not tested this)
